# Generated by Django 3.1.4 on 2020-12-09 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = ('contenttypes', '0002_remove_content_type_name'),

    operations = [
        migrations.CreateModel(
            name='RecordedModelRun',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('polymorphic_ctype',
                 models.ForeignKey(
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='polymorphic_h1sttrust.recordedmodelrun_set+',
                    to='contenttypes.contenttype'))
            ],

            options={
                'verbose_name': 'Recorded Model Run',
                'verbose_name_plural': 'Recorded Model Runs',
                'db_table': 'H1stTrust_RecordedModelRun',
                'default_related_name': 'recorded_model_runs'
            }
        ),

        migrations.CreateModel(
            name='RecordedModelFittingRun',

            fields=[
                ('recordedmodelrun_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='recorded_model_fitting_runs',
                    serialize=False, to='H1stTrust.recordedmodelrun'))
            ],

            options={
                'verbose_name': 'Recorded Model Fitting Run',
                'verbose_name_plural': 'Recorded Model Fitting Runs',
                'db_table': 'H1stTrust_RecordedModelFittingRun',
                'default_related_name': 'recorded_model_fitting_runs'
            },

            bases=('H1stTrust.recordedmodelrun',)
        ),

        migrations.CreateModel(
            name='RecordedModelInferenceRun',

            fields=[
                ('recordedmodelrun_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='recorded_model_inference_runs',
                    serialize=False,
                    to='H1stTrust.recordedmodelrun'))
            ],

            options={
                'verbose_name': 'Recorded Model Inference Run',
                'verbose_name_plural': 'Recorded Model Inference Runs',
                'db_table': 'H1stTrust_RecordedModelInferenceRun',
                'default_related_name': 'recorded_model_inference_runs'
            },

            bases=('H1stTrust.recordedmodelrun',)
        )
    ]
