# Generated by Django 3.1.4 on 2020-12-11 01:07


import django.core.serializers.json
from django.db import migrations, models

import h1st.django.util.git
import h1st.django.util.pip

import json.decoder


class Migration(migrations.Migration):
    dependencies = ('H1stTrust', '0002_Decision_GitHash_PyDeps'),

    operations = [
        migrations.AddField(
            model_name='decision',
            name='git_repo_head_commit_hash',
            field=models.CharField(
                    blank=True,
                    db_index=True,
                    default=h1st.django.util.git.get_git_repo_head_commit_hash,
                    help_text='Git Repository Head Commit Hash',
                    max_length=40,
                    null=True,
                    verbose_name='Git Repository Head Commit Hash')
        ),

        migrations.AddField(
            model_name='decision',
            name='python_dependencies',
            field=models.JSONField(
                    decoder=json.decoder.JSONDecoder,
                    default=h1st.django.util.pip.get_python_dependencies,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Python Dependencies',
                    verbose_name='Python Dependencies')
        )
    ]
