# Generated by Django 3.1.4 on 2020-12-15 05:23


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import json.decoder


class Migration(migrations.Migration):
    dependencies = ('H1stTrust', '0002_Decision_GitHash_PyDeps'),

    operations = \
        migrations.CreateModel(
            name='ImmutableJSONDataSet',

            fields=[
                ('immutabledataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='immutable_json_data_sets',
                    serialize=False,
                    to='H1stTrust.immutabledataset')),

                ('json',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Immutable JSON Data Content',
                    null=True,
                    verbose_name='Immutable JSON Data Content'))
            ],

            options={
                'verbose_name': 'Immutable JSON Data Set',
                'verbose_name_plural': 'Immutable JSON Data Sets',
                'db_table': 'H1stTrust_ImmutableJSONDataSet',
                'abstract': False,
                'default_related_name': 'immutable_json_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('H1stTrust.immutabledataset',)
        ),
