# Generated by Django 3.1.4 on 2020-12-09 00:57


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import h1st.core.model

import json.decoder
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('H1stData', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='H1stDjangoModel',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('polymorphic_ctype',
                 models.ForeignKey(
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='polymorphic_h1stmodel.h1stdjangomodel_set+',
                    to='contenttypes.contenttype'))
            ],

            options={
                'verbose_name': 'H1st Model',
                'verbose_name_plural': 'H1st Models',
                'db_table': 'H1stModel_H1stDjangoModel',
                'default_related_name': 'h1st_models'
            },

            bases=(models.Model,
                   h1st.core.model.Model)
        ),

        migrations.CreateModel(
            name='Decision',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('data_set',
                 models.ForeignKey(
                    help_text='Data Set used in Decision',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='decisions',
                    related_query_name='decision',
                    to='H1stData.dataset',
                    verbose_name='Data Set')),

                ('h1st_model',
                 models.ForeignKey(
                    help_text='H1st Model used in Decision',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='decisions',
                    related_query_name='decision',
                    to='H1stModel.h1stdjangomodel',
                    verbose_name='H1st Model')),

                ('output_json',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Output (JSON) of Decision',
                    null=True,
                    verbose_name='Output (JSON)'))
            ],

            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'db_table': 'H1stModel_Decision',
                'default_related_name': 'decisions'
            }
        ),

        migrations.CreateModel(
            name='H1stModelEvalMetricsSet',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('h1st_model',
                 models.ForeignKey(
                    help_text='H1st Model evaluated',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='h1st_model_eval_metrics_sets',
                    related_query_name='h1st_model_eval_metrics_set',
                    to='H1stModel.h1stdjangomodel',
                    verbose_name='H1st Model')),

                ('data_set',
                 models.ForeignKey(
                    help_text='Data Set for evaluation',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='h1st_model_eval_metrics_sets',
                    related_query_name='h1st_model_eval_metrics_set',
                    to='H1stData.dataset',
                    verbose_name='Data Set')),

                ('eval_metrics',
                 models.JSONField(
                    decoder=json.decoder.JSONDecoder,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Evaluation Metrics',
                    verbose_name='Evaluation Metrics'))
            ],

            options={
                'verbose_name': 'H1st Model Evaluation Metrics Set',
                'verbose_name_plural': 'H1st Model Evaluation Metrics Sets',
                'db_table': 'H1stModel_H1stModelEvalMetricsSet',
                'default_related_name': 'h1st_model_eval_metrics_sets'
            }
        )
    ]
