# Generated by Django 3.1.5 on 2021-01-27 09:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('H1stModel', '0002_graph'),

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='created',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='polymorphic_ctype',
        ),

        migrations.AddField(
            model_name='graph',
            name='model_ptr',
            field=models.OneToOneField(
                    auto_created=True,
                    default='45f90f21-4e24-43c6-b4c3-414b0fae5c1c',
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='h1st_graphs',
                    serialize=False,
                    to='H1stModel.model'),
            preserve_default=False,
        )
    ]
