# Generated by Django 3.1.3 on 2020-11-29 08:17


from django.db import migrations, models
import django.db.models.deletion

import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = ('contenttypes', '0002_remove_content_type_name'),

    operations = \
        migrations.CreateModel(
            name='Dataset',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('polymorphic_ctype',
                 models.ForeignKey(
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='polymorphic_h1stdata.dataset_set+',
                    to='contenttypes.contenttype')),
            ],

            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
