# Generated by Django 3.1.3 on 2020-11-29 09:23


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = ('H1stData', '0001_initial'),

    operations = \
        migrations.AlterModelOptions(
            name='dataset',
            options={
                'default_related_name': 'datasets',
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets'
            },
        ), \
        \
        migrations.AlterModelTable(
            name='dataset',
            table='H1stData_Dataset',
        ),
