# Generated by Django 3.1.3 on 2020-12-01 18:02


from django.db import migrations, models
import django.db.models.deletion

import uuid


class Migration(migrations.Migration):
    dependencies = \
        ('contenttypes', '0002_remove_content_type_name'), \
        ('H1stData', '0001_initial')

    operations = \
        migrations.CreateModel(
            name='DataSchema',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('polymorphic_ctype',
                 models.ForeignKey(
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='polymorphic_h1stdata.dataschema_set+',
                    to='contenttypes.contenttype'))
            ],

            options={
                'verbose_name': 'Data Schema',
                'verbose_name_plural': 'Data Schemas',
                'db_table': 'H1stData_DataSchema',
                'default_related_name': 'data_schemas'
            }
        ),
