# Generated by Django 3.1.3 on 2020-12-01 19:06


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import json.decoder
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('H1stData', '0001_initial'),
        ('H1stModel', '0001_initial')
    ]

    operations = \
        migrations.CreateModel(
            name='Decision',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('data_set',
                 models.ForeignKey(
                    help_text='Data Set used in Decision',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='decisions',
                    related_query_name='decision',
                    to='H1stData.dataset',
                    verbose_name='Data Set')),

                ('h1st_model',
                 models.ForeignKey(
                    help_text='H1st Model used in Decision',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='decisions',
                    related_query_name='decision',
                    to='H1stModel.h1stmodel',
                    verbose_name='H1st Model')),

                ('output_json',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Output (JSON) of Decision',
                    null=True,
                    verbose_name='Output (JSON)'))
            ],

            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'db_table': 'H1stTrust_Decision',
                'default_related_name': 'decisions'
            }
        ),
