# Generated by Django 3.1.3 on 2020-11-29 08:51


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import json.decoder
import uuid


class Migration(migrations.Migration):
    dependencies = \
        ('H1stData', '0001_initial'), \
        ('H1stModel', '0001_initial')

    operations = \
        migrations.CreateModel(
            name='H1stModelEvalMetricsSet',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('h1st_model',
                 models.ForeignKey(
                    help_text='H1st Model evaluated',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='h1st_model_eval_metrics_sets',
                    related_query_name='h1st_model_eval_metrics_set',
                    to='H1stModel.h1stmodel',
                    verbose_name='H1st Model')),

                ('dataset',
                 models.ForeignKey(
                    help_text='Dataset for evaluation',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='h1st_model_eval_metrics_sets',
                    related_query_name='h1st_model_eval_metrics_set',
                    to='H1stData.dataset',
                    verbose_name='Dataset')),

                ('eval_metrics',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Evaluation Metrics',
                    null=True,
                    verbose_name='Evaluation Metrics')),
            ],
        ),
