# Generated by Django 3.1.3 on 2020-11-29 09:29


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = ('H1stModel', '0002_H1stModelEvalMetricsSet'),

    operations = \
        migrations.AlterModelOptions(
            name='h1stmodel',
            options={
                'default_related_name': 'h1st_models',
                'verbose_name': 'H1st Model',
                'verbose_name_plural': 'H1st Models'
            },
        ), \
        \
        migrations.AlterModelOptions(
            name='h1stmodelevalmetricsset',
            options={
                'default_related_name': 'h1st_model_eval_metrics_sets',
                'verbose_name': 'H1st Model Evaluation Metrics Set',
                'verbose_name_plural': 'H1st Model Evaluation Metrics Sets'
            },
        ), \
        \
        migrations.AlterModelTable(
            name='h1stmodel',
            table='H1stModel_H1stModel',
        ), \
        \
        migrations.AlterModelTable(
            name='h1stmodelevalmetricsset',
            table='H1stModel_H1stModelEvalMetricsSet',
        )
