# Generated by Django 3.1.4 on 2020-12-10 12:06


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import model_utils.fields

import json.decoder
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = ('contenttypes', '0002_remove_content_type_name'),

    operations = [
        migrations.CreateModel(
            name='DataSchema',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    help_text='UUID',
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('name',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Schema Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Data Schema Unique Name')),

                ('specs',
                 models.JSONField(
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Data Schema Specifications',
                    verbose_name='Data Schema Specifications')),

                ('created',
                 model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='created')),
                ('modified',
                 model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='modified')),

                ('polymorphic_ctype',
                 models.ForeignKey(
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='polymorphic_h1stdata.dataschema_set+',
                    to='contenttypes.contenttype'))
            ],

            options={
                'verbose_name': 'Data Schema',
                'verbose_name_plural': 'Data Schemas',
                'db_table': 'H1stData_DataSchema',
                'ordering': ('name',),
                'default_related_name': 'data_schemas'
            }
        ),

        migrations.CreateModel(
            name='DataSet',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    help_text='UUID',
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('name',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Data Set Unique Name')),

                ('schema',
                 models.ForeignKey(
                    blank=True,
                    default=None,
                    help_text='Data Set Schema',
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='data_sets',
                    related_query_name='data_set',
                    to='H1stData.dataschema',
                    verbose_name='Data Set Schema')),

                ('created',
                 model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='created')),

                ('modified',
                 model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='modified')),

                ('polymorphic_ctype',
                 models.ForeignKey(
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='polymorphic_h1stdata.dataset_set+',
                    to='contenttypes.contenttype'))
            ],

            options={
                'verbose_name': 'Data Set',
                'verbose_name_plural': 'Data Sets',
                'db_table': 'H1stData_DataSet',
                'ordering': ('name',),
                'default_related_name': 'data_sets'
            }
        ),

        migrations.CreateModel(
            name='JSONDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='json_data_sets',
                    serialize=False,
                    to='H1stData.dataset')),

                ('json',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='JSON Data Content',
                    null=True,
                    verbose_name='JSON Data Content'))
            ],

            options={
                'verbose_name': 'JSON Data Set',
                'verbose_name_plural': 'JSON Data Sets',
                'db_table': 'H1stData_JSONDataSet',
                'abstract': False,
                'default_related_name': 'json_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('H1stData.dataset',)
        ),

        migrations.CreateModel(
            name='FileStoredDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='file_stored_data_sets',
                    serialize=False,
                    to='H1stData.dataset')),

                ('path',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Directory/File/URL Path',
                    max_length=255,
                    verbose_name='Data Set Directory/File/URL Path'))
            ],

            options={
                'verbose_name': 'File-Stored Data Set',
                'verbose_name_plural': 'File-Stored Data Sets',
                'db_table': 'H1stData_FileStoredDataSet',
                'abstract': False,
                'default_related_name': 'file_stored_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('H1stData.dataset',)
        ),

        migrations.CreateModel(
            name='ParquetDataSet',

            fields=[
                ('filestoreddataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='parquet_data_sets',
                    serialize=False,
                    to='H1stData.filestoreddataset'))
            ],

            options={
                'verbose_name': 'Parquet Data Set',
                'verbose_name_plural': 'Parquet Data Sets',
                'db_table': 'H1stData_ParquetDataSet',
                'abstract': False,
                'default_related_name': 'parquet_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('H1stData.filestoreddataset',)
        )
    ]
