# Generated by Django 3.1.4 on 2020-12-15 05:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('H1stData', '0001_initial'),

    operations = \
        migrations.CreateModel(
            name='TFRecordDataSet',

            fields=[
                ('filestoreddataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='tfrecord_data_sets',
                    serialize=False,
                    to='H1stData.filestoreddataset'))
            ],

            options={
                'verbose_name': 'TensorFlow Record Data Set',
                'verbose_name_plural': 'TensorFlow Record Data Sets',
                'db_table': 'H1stData_TFRecordDataSet',
                'abstract': False,
                'default_related_name': 'tfrecord_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('H1stData.filestoreddataset',)
        ),
