# Generated by Django 3.1.4 on 2020-12-09 01:28


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import json.decoder


class Migration(migrations.Migration):
    dependencies = ('H1stData', '0001_initial'),

    operations = \
        migrations.CreateModel(
            name='JSONDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='json_data_sets',
                    serialize=False, to='H1stData.dataset')),

                ('json',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='JSON Data Content',
                    null=True,
                    verbose_name='JSON Data Content'))
            ],

            options={
                'verbose_name': 'JSON Data Set',
                'verbose_name_plural': 'JSON Data Sets',
                'db_table': 'H1stData_JSONDataSet',
                'default_related_name': 'json_data_sets'
            },

            bases=('H1stData.dataset',)
        ),
