# Generated by Django 3.1.4 on 2020-12-09 07:58


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('H1stData', '0002_JSONDataSet'),

    operations = \
        migrations.CreateModel(
            name='FileBasedDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='file_based_data_sets',
                    serialize=False, to='H1stData.dataset')),

                ('path',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Path',
                    max_length=255,
                    verbose_name='Path'))
            ],

            options={
                'verbose_name': 'File-Based Data Set',
                'verbose_name_plural': 'File-Based Data Sets',
                'db_table': 'H1stData_FileBasedDataSet',
                'default_related_name': 'file_based_data_sets'
            },

            bases=('H1stData.dataset',)
        ),
