# Generated by Django 3.1.4 on 2020-12-09 08:20


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('H1stData', '0003_FileBasedDataSet'),

    operations = \
        migrations.CreateModel(
            name='ParquetDataSet',

            fields=[
                ('filebaseddataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='parquet_data_sets',
                    serialize=False,
                    to='H1stData.filebaseddataset'))
            ],

            options={
                'verbose_name': 'Parquet Data Set',
                'verbose_name_plural': 'Parquet Data Sets',
                'db_table': 'H1stData_ParquetDataSet',
                'default_related_name': 'parquet_data_sets'
            },

            bases=('H1stData.filebaseddataset',)
        ),
